# Generated by Django 5.2.6 on 2025-09-23 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, limit_choices_to={'patient__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.user'),
        ),
    ]
